### ISSUE TITLE
Dados não carregam

### ISSUE THREAD

**Issue by insidegui** [CocoaHeadsConference/CHConferenceApp#17]
Alguns usuários estão reportando que o app não carrega os dados do evento ao ser rodado.

Dois reports:
1 - iPhone 6s, iOS 10.1.1, resolvido após trocar de rede
2 - iPhone 6 Plus, iOS 10.1.1, não resolvido

![confapp_1024](https://cloud.githubusercontent.com/assets/67184/20810657/aca032bc-b7f1-11e6-9d54-0ffc482168b0.jpg)

**Comment by brunogb** [comment]
O primeiro era falta de conexão, então não tem muito o que ser feito (alem de exibir um alerta na tela). O segundo reportou que a lista de palestrantes aparece, o que é estranho pois a chamada do json é unica pro app inteiro, e o parser ocorre como bloco (ou tudo funciona ou tudo falha)
Por isso se apareceu os palestrantes é porque o json foi carregado com sucesso. Vou dar uma testada aqui

**Comment by brunogb** [comment]
Deveria estar corrigido com o 456700c446928b009127a6a422550dcbc4f9f801

Abri o PR #18 que trata disso tambem

**Comment by ltsuda** [comment]
Atualizei o repo aqui e subi pro iPhone, funcionando tudo agora. 

Obrigado pela correção. 💯
