### ISSUE TITLE
Adicionar WebView para site dos patrocinadores

### ISSUE THREAD

**Issue by brunogb** [CocoaHeadsConference/CHConferenceApp#3]
Precisamos exibir em uma WebView o site do patrocinador quando o usuario o selecionar na lista de patrocinadores

**Comment by marcelofabri** [comment]
`SFSafariViewController`?

**Comment by brunogb** [comment]
Tinha pensado nele, mas tambem podemos fazer um embed so do WebView para o usuario não sair da pagina do anunciante. 

Olhando outros apps eles tem feito desse jeito

**Comment by marcelofabri** [comment]
eu sou mais o `SFSafariViewController` pela usabilidade e facilidade de implementar 😅
