### ISSUE TITLE
Criar tela de erro para caso o download do JSON dê errado

### ISSUE THREAD

**Issue by loloop** [CocoaHeadsConference/CHConferenceApp#54]
É necessário que essa tela tenha um botão de retry

**Comment by douglastaquary** [comment]
Verdade. Bem lembrado .. e no caso da tela de Schedule? Pq mesmo que na home tenha um retry button, se o cara trocar pra tela de schedule tem q ter o emptyState também.

**Comment by loloop** [comment]
Se o JSON não baixar acho que a gente nem mostra a tab, mais fácil

**Comment by douglastaquary** [comment]
Entendi ... vi o que vc fez lá ! Gostei da ideia. Ali a gente ajusta para ter um botão de retry. 
Por enquanto vamos colocar uma mensagem mais explicativa. Algo do tipo.

**Comment by loloop** [comment]
Sim, claro! Deixei lá meio de placeholder pra alguém poder pegar e fazer isso, não preciso entregar os 2 juntos no mesmo PR
